spring:
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=Capybook;encrypt=true;trustServerCertificate=true;"
    username: sa
    password: sa
  application:
    name: capybook
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: file:./uploads/
  security:
    user:
      name: sa
      password: sa
  jpa:
    open-in-view: false

server:
  port: 6789

logging:
  level:
    root: warn

jwt:
  signerKey: "lIAz1lQmNF5SFv8vfKBByIeXSlgBFkptJHv+pjfckpowfs+ZXG35CDk9WHRfkiZF"


