spring:
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=Capybook;encrypt=true;trustServerCertificate=true;"
    username: sa
    password: sa
  application:
    name: capybook
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 6789

logging:
  level:
    root: warn

